### ISSUE TITLE
Drop Support of Php 7.2 and 7.3?

### ISSUE THREAD

**Issue by Chris53897** [omines/datatables-bundle#253]
Can we move on to Php >= 7.3  or >= 7.4 ?
See Stats for actual usage of php versions.
https://packagist.org/packages/omines/datatables-bundle/php-stats#0.5

**Comment by Ahummeling** [comment]
I think it would make more sense to drop support for php 7 all together, instead of just the lowest 2 versions. But seeing as the majority of the userbase is still on 7.4, I don't think the time has come for that yet. As far as I know, there are not really any critical features in php7.4 that are not in 7.3 or 7.2. Maybe you could elaborate a bit more on the reason for dropping support?

**Comment by maxhelias** [comment]
IMO ">= 7.4" it's ok because the others are at end of life and no longer receive security patches

**Comment by Ahummeling** [comment]
It would still introduce a BC breaking change. I am not sure about how BC is treated normally in 0.x versions of bundles, but I know that if we drop support for 7.2 and 7.3, we should at least think about which version we should tag the including release as.

**Comment by Chris53897** [comment]
It is not a BC in semver because of the handling from composer. It just could not be updated. Of course i would like to go to php8 directly ;). But to much users have 7.4 installed.

With 7.3/7.4 we can drop dependencies and upgrade them to higher versions.
PhpUnit 9 by example.
https://packagist.org/packages/phpunit/phpunit#9.5.11

And integrate the new language features.

**Comment by Ahummeling** [comment]
Oh yeah ofcourse, oops. In that case I agree that dropping support for php7.2 and php7.3 is OK :+1:

**Comment by Chris53897** [comment]
master is now already on `"php": ">=8.0"`
i will close this.
