### ISSUE TITLE
Omines datadables bundle with api platform request

### ISSUE THREAD

**Issue by cymard** [omines/datatables-bundle#276]
Hello,

I want to use omines datadables bundle with api platform request, is it possible to use it with the custom adapter, and if it’s possible, how ?

Thank you

**Comment by Chris53897** [comment]
Hi @cymard
If you found a solution please let us know. Sounds interesting.

**Comment by curry684** [comment]
Connecting to arbitrary APIs is out of scope for this bundle. It should be relatively easy to implement using a custom adapter, but not something we can provide an abstraction layer for easily since every detail would have to be customizable (authentication, formats, data mapping, filtering etc.). If something needs to be 100% customizable, just create a custom adapter.

As this issue does not relate to the bundle itself I'm closing this here.
