### ISSUE TITLE
Case-Insensitive Search

### ISSUE THREAD

**Issue by Chris53897** [omines/datatables-bundle#277]
Hi, 
is there an easy was to make a switch between case-sensitive and `case-insensitive` search?
Actual the search is case-sensitive and users are complaining about not finding items.

Greetz

**Comment by curry684** [comment]
This depends completely on the adapter and is not something we can do so many abstraction levels higher.

Most likely your actual problem is that you are not using case insensitive collation in your database, as the base ORM adapter just searches with `LIKE` statements. If you use the recommended database collation of `utf8mb4_general_ci` all searches from this bundle are automatically case insensitive.

**Comment by Chris53897** [comment]
Thanks for the fast response. I will test it
